dist: trusty
language: java
services:
  - docker
script:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    mvn -B -Pprod,hosted -DskipTests clean install -pl reader-web,reader-core,reader-web-common;
    else
    mvn -B test;
    fi
after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    docker build -f reader-distribution-docker/Dockerfile -t sismics/reader:latest .;
    curl -u $DOCKER_USERNAME:$DOCKER_API_KEY https://cloud.docker.com/api/app/v1/service/;
    docker push sismics/reader:latest;
    fi
