dist: trusty
language: java
services:
  - docker
script:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    mvn -B -Pprod,hosted -DskipTests clean install -pl reader-web,reader-core,reader-web-common;
    else
    mvn -B test;
    fi
after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    docker build -f reader-distribution-docker/Dockerfile -t sismics/reader:latest .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sismics/reader:latest;
    fi
